name: Deploy on refactor push
on:
  push:
    branches:
    - refactor
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger rebuild on vercel
        run: curl -X POST ${{ secrets.REFACTOR_DEPLOY_HOOK }}
